from abc import ABC, abstractmethod
from typing import List

from app.models.security_event import SecurityEvent
from app.schemas.alert import AlertCreate

class BaseDetectionRule(ABC):
    @property
    @abstractmethod
    def rule_name(self) -> str:
        """Name of the detection rule"""
        pass

    @property
    @abstractmethod
    def alert_type(self) -> str:
        """The type of alert this rule generates"""
        pass

    @property
    @abstractmethod
    def severity(self) -> str:
        """The default severity of alerts generated by this rule"""
        pass

    @abstractmethod
    def analyze(self, events: List[SecurityEvent]) -> List[AlertCreate]:
        """
        Analyze a batch of security events and return a list of AlertCreate schemas
        for any identified threats.
        """
        pass
