from app.database.session import SessionLocal
from app.models.security_event import SecurityEvent
from app.models.alert import Alert
from app.detection.rules.new_device import NewDeviceRule

db = SessionLocal()
events = db.query(SecurityEvent).all()
print(f"Total events in DB: {len(events)}")

rule = NewDeviceRule()
alerts = rule.analyze(events)
print(f"Alerts generated by rule directly: {len(alerts)}")

db.close()
