import asyncio
from app.database.session import SessionLocal
from app.detection.rules.new_device import NewDeviceRule
from app.simulators.scenarios import get_new_device
from datetime import datetime
from app.models.alert import Alert

# 1. Create a mock event from simulator
events = get_new_device(datetime.now(), "debug_scenario_1")
event_data = events[0]
print("Event data generated by simulator:", event_data)

# Let's see if we can instantiate SecurityEvent
from app.models.security_event import SecurityEvent

db_event = SecurityEvent(**event_data)
# Fake ID
db_event.id = 1

print("Event payload type:", type(db_event.raw_payload))
print("Event payload:", db_event.raw_payload)

rule = NewDeviceRule()
alerts = rule.analyze([db_event])
print("Alerts generated:", alerts)
